--- a/Dockerfile
+++ b/Dockerfile
@@ -1,3 +1,5 @@
 ARG BUILD_FROM=ghcr.io/home-assistant/base-python:3.14-alpine3.24-2026.08.0
+ARG EXTRA_INDEX_URL="https://villgzs.github.io/musllinux-index/"
+ARG PIP_EXTRA_INDEX_URL="https://villgzs.github.io/musllinux-index/"
 ####
 ## Builder stage for ssocr, installs to /opt/ssocr
@@ -159,6 +161,7 @@ RUN \
     --mount=type=bind,src=./requirements.txt,dst=/tmp/requirements.txt \
     --mount=type=cache,target=/root/.cache/pip,sharing=locked,id=pip-cache-${BUILD_FROM} \
     pip3 install --only-binary=:all: \
+        --extra-index-url https://villgzs.github.io/musllinux-index \
         -r /tmp/requirements.txt
 
 WORKDIR /usr/src/
