--- a/alpine/Dockerfile
+++ b/alpine/Dockerfile
@@ -52,6 +52,7 @@
 
 # Sanity check for later steps
 ARG TARGETARCH
+ARG TARGETVARIANT
 RUN \
     if [ -z "${TARGETARCH}" ]; then \
         echo "TARGETARCH is not set, please use Docker BuildKit for the build." && exit 1; \
@@ -98,6 +99,18 @@
             S6_OVERLAY_ARCH="${S6_OVERLAY_ARCH:-aarch64}" \
             TEMPIO_ARCH="${TEMPIO_ARCH:-aarch64}" \
             ;; \
+        arm) \
+            case "${TARGETVARIANT}" in \
+                v7) \
+                    S6_OVERLAY_ARCH="${S6_OVERLAY_ARCH:-arm}" \
+                    TEMPIO_ARCH="${TEMPIO_ARCH:-armv7}" \
+                    ;; \
+                v6) \
+                    S6_OVERLAY_ARCH="${S6_OVERLAY_ARCH:-arm}" \
+                    TEMPIO_ARCH="${TEMPIO_ARCH:-armhf}" \
+                    ;; \
+            esac \
+            ;; \
     esac \
     && echo "Selected from TARGETARCH=${TARGETARCH} arch-specific" \
         " S6_OVERLAY_ARCH=${S6_OVERLAY_ARCH:=${TARGETARCH}}" \
