# syntax=docker/dockerfile@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769
# Partly generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
ARG BUILD_FROM=ghcr.io/villgzs/basic-added:latest
FROM ${BUILD_FROM}

LABEL \
    io.hass.type="core" \
    org.opencontainers.image.authors="The Home Assistant Authors" \
    org.opencontainers.image.description="Open-source home automation platform running on Python 3" \
    org.opencontainers.image.documentation="https://www.home-assistant.io/docs/" \
    org.opencontainers.image.licenses="Apache-2.0" \
    org.opencontainers.image.title="Home Assistant" \
    org.opencontainers.image.url="https://www.home-assistant.io/"

# Synchronize with homeassistant/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

WORKDIR /usr/src

# Home Assistant S6-Overlay
COPY rootfs /

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc:1.9.14@sha256:675c318b23c06fd862a61d262240c9a63436b4050d177ffc68a32710d9e05bae /usr/local/bin/go2rtc /bin/go2rtc

## Setup Home Assistant Core dependencies
COPY --parents requirements.txt homeassistant/package_constraints.txt homeassistant/

## RUN --network=host \
RUN \
    # Verify go2rtc can be executed
    go2rtc --version \
    && apk add --no-cache libffi libjpeg-turbo zlib freetype \
    && apk add --no-cache --virtual .build-deps cmake make ninja gcc g++ musl-dev rust cargo linux-headers libffi-dev jpeg-dev zlib-dev freetype-dev \
    # Install uv at the version pinned in the requirements file
    && pip3 install --no-cache-dir "uv==$(awk -F'==' '/^uv==/{print $2}' homeassistant/requirements.txt)" \
    && uv pip install \
        --index-strategy unsafe-best-match \
        -r homeassistant/requirements.txt \
    && apk del --no-cache .build-deps
    
#RUN --network=host \
#    # Verify go2rtc can be executed
#    go2rtc --version \
#    # Install uv at the version pinned in the requirements file
#    && pip3 install --no-cache-dir "uv==$(awk -F'==' '/^uv==/{print $2}' homeassistant/requirements.txt)" \
#    && uv pip install \
#        --index-strategy unsafe-best-match \
#        -r homeassistant/requirements.txt
#

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* homeassistant/
RUN \
#    apk add --no-cache --virtual .build-deps autoconf cmake make ninja gcc g++ musl-dev rust cargo linux-headers libffi-dev jpeg-dev zlib-dev freetype-dev ffmpeg-dev pkgconf gfortran  openblas-dev libxml2-dev libxslt-dev mariadb-dev postgresql-dev glib-dev openssl-dev\
#   && apk add --no-cache ffmpeg-libs libavc1394 openblas libgfortran libxml2 libxslt mariadb-connector-c-dev postgresql-libs\
    apk add --no-cache --virtual .build-deps autoconf cmake make ninja gcc g++ musl-dev rust cargo linux-headers libffi-dev jpeg-dev zlib-dev freetype-dev ffmpeg-dev pkgconf gfortran openblas-dev libxml2-dev libxslt-dev mariadb-dev postgresql-dev glib-dev openssl-dev mariadb-connector-c-dev \
    && apk add --no-cache ffmpeg-libs libavc1394 openblas libgfortran libxml2 libxslt mariadb-connector-c postgresql-libs \
    &&if ls homeassistant/home_assistant_*.whl 1> /dev/null 2>&1; then \
        uv pip install homeassistant/home_assistant_*.whl; \
    fi \
    && uv pip install \
        -r homeassistant/requirements_all.txt \
        --index-strategy unsafe-best-match \
    && apk del --no-cache .build-deps
    

## Setup Home Assistant Core
COPY --parents LICENSE* README* homeassistant/ pyproject.toml homeassistant/
RUN \
    echo "Setup Home Assistant Core" \
    uv pip install \
        --index-strategy unsafe-best-match \
        -e ./homeassistant \
    && python3 -m compileall \
        homeassistant/homeassistant

WORKDIR /config
